services:
  - type: web
    name: django-fyp-project
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn ai_complaints_system.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*,https://django-fyp-project.onrender.com"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: django-fyp-project-db
          property: connectionString
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false

databases:
  - name: django-fyp-project-db
    databaseName: django_fyp
    user: django_user