# Generated by Django 5.0.6 on 2026-05-11 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_add_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_classified',
            field=models.BooleanField(default=False, help_text='Whether this complaint was processed by AI classifier'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_confidence_score',
            field=models.FloatField(default=0.0, help_text='AI model confidence score for classification (0-100)'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='attachment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(blank=True, choices=[('academic', 'Academic'), ('ict', 'ICT'), ('admin', 'Administration'), ('student_affairs', 'Student Affairs'), ('other', 'Other')], help_text='Department this complaint is routed to', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='student_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdminQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField(help_text='Full complaint text for review')),
                ('category', models.CharField(help_text="Classification category (usually 'Other')", max_length=50)),
                ('reason', models.TextField(help_text='Reason why this complaint requires admin review')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending_review', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes on review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_queue', to='complaints.complaint')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admin_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
